## DATA PREPROCESSING

### Importing dataset

In [39]:
import pandas as pd

In [40]:
df = pd.read_csv('Restaurant_Reviews.tsv', delimiter = '\t', quoting = 3)

In [41]:
X = df.drop("Liked",axis=1)

In [42]:
y = df['Liked']

In [43]:
X.shape

(1000, 1)

In [44]:
y.shape

(1000,)

In [45]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

### Initializing dictionary size

In [46]:
voc_size = 10000

In [47]:
reviews = X.copy()

In [48]:
reviews['Review'][1]

'Crust is not good.'

In [49]:
import nltk
import re
from nltk.corpus import stopwords

In [50]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/cod3bug/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [51]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(reviews)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', reviews['Review'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [52]:
corpus

['wow love place',
 'crust good',
 'tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch',
 'servic prompt',
 'would go back',
 'cashier care ever say still end wayyy overpr',
 'tri cape cod ravoli chicken cranberri mmmm',
 'disgust pretti sure human hair',
 'shock sign indic cash',
 'highli recommend',
 'waitress littl slow servic',
 'place worth time let alon vega',
 'like',
 'burritto blah',
 'food amaz',
 'servic also cute',
 'could care less interior beauti',
 'perform',
 'right red velvet cake ohhh stuff good',
 'never brought salad ask',
 'hole wall great mexican street taco friendli staff',
 'took hour get food tabl restaur food luke warm sever run around like total overwhelm',
 'worst salmon sashimi',
 'also combo like burger fri beer decent deal',
 'like final blow',
 'found place acc

In [53]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[1710, 4511, 302],
 [6030, 5043],
 [7624, 1793, 9312],
 [1807, 7660, 8986, 5794, 4251, 4552, 7376, 3726, 4511],
 [292, 8154, 7732, 4427],
 [9489, 8192, 1832, 6197, 8233],
 [2509, 6977, 2812],
 [9788, 9599, 7517, 8234, 9959, 9162, 5478, 9518, 50, 5761],
 [4635, 7732],
 [7732, 1659],
 [36, 675],
 [1421, 2248, 6060],
 [1388, 5594, 1712, 3721, 5971, 5842, 2734, 1193],
 [1951, 2522, 6537, 3338, 7278, 998, 7399],
 [7153, 6658, 5748, 2907, 7533],
 [2541, 1912, 4920, 6896],
 [2430, 3726],
 [7163, 2643, 4028, 36],
 [302, 8909, 9518, 5677, 6108, 3599],
 [9599],
 [2810, 4082],
 [8494, 3384],
 [36, 1090, 346],
 [8234, 5594, 9515, 6914, 3683],
 [4134],
 [4692, 583, 8667, 2731, 5416, 917, 5043],
 [4019, 3710, 6414, 1107],
 [3847, 7865, 7732, 364, 5191, 7580, 4522, 5917],
 [3014,
  6571,
  9489,
  8494,
  7998,
  9301,
  8494,
  8807,
  551,
  4884,
  3223,
  1587,
  9599,
  6998,
  6676],
 [8059, 7984, 3229],
 [1090, 1096, 9599, 90, 4635, 5909, 6546, 7083],
 [9599, 9605, 1380],
 [4536, 302, 709, 82

In [54]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1710 4511  302]
 [   0    0    0 ...    0 6030 5043]
 [   0    0    0 ... 7624 1793 9312]
 ...
 [   0    0    0 ... 1421 2248 6060]
 [   0    0    0 ... 8191  637 9518]
 [   0    0    0 ... 3014 4960 9009]]


In [55]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0, 1710, 4511,  302], dtype=int32)

### Generating the architecture of LSTM 

In [56]:
from tensorflow.keras.layers import Dropout
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [57]:
len(embedded_docs),y.shape

(1000, (1000,))

In [58]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [59]:
X_final.shape,y_final.shape

((1000, 20), (1000,))

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Training the model

In [61]:
model.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test))

Epoch 1/50
21/21 [==============================] - 2s 32ms/step - loss: 0.6924 - accuracy: 0.5228 - val_loss: 0.6938 - val_accuracy: 0.4758
Epoch 2/50
21/21 [==============================] - 0s 10ms/step - loss: 0.6873 - accuracy: 0.5851 - val_loss: 0.6832 - val_accuracy: 0.6424
Epoch 3/50
21/21 [==============================] - 0s 10ms/step - loss: 0.6642 - accuracy: 0.7123 - val_loss: 0.6528 - val_accuracy: 0.7091
Epoch 4/50
21/21 [==============================] - 0s 9ms/step - loss: 0.5926 - accuracy: 0.8199 - val_loss: 0.5557 - val_accuracy: 0.7303
Epoch 5/50
21/21 [==============================] - 0s 11ms/step - loss: 0.3846 - accuracy: 0.8810 - val_loss: 0.5184 - val_accuracy: 0.7455
Epoch 6/50
21/21 [==============================] - 0s 9ms/step - loss: 0.2709 - accuracy: 0.9151 - val_loss: 0.5646 - val_accuracy: 0.7576
Epoch 7/50
21/21 [==============================] - 0s 10ms/step - loss: 0.1546 - accuracy: 0.9523 - val_loss: 0.6027 - val_accuracy: 0.7727
Epoch 8/50
21/2

In [62]:
from sklearn.metrics import confusion_matrix

In [63]:
y_pred=model.predict_classes(X_test)
confusion_matrix(y_test,y_pred)

array([[134,  39],
       [ 44, 113]])

In [64]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7484848484848485

### Predicting result on normal text input 

In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(max_features = 1000)
cv.fit(corpus)

TfidfVectorizer(max_features=1000)

In [72]:
pred = ["The food was bad"]
vect = cv.transform(pred).toarray()

In [73]:
if model.predict(vect)[0] >= 0.5:
    print("Positive")
else:
    print("Negative")

Negative
